In [1]:
#Cargamos las librerías a utilizar
import pandas as pd
import numpy as np
from scipy.linalg import svd




In [29]:
X=  [[1,0,1,0],  
    [0,1,0,1]]  
X


[[1, 0, 1, 0], [0, 1, 0, 1]]

In [30]:
U, S, Vt = svd(X)
U 

array([[1., 0.],
       [0., 1.]])

In [31]:
S

array([1.41421356, 1.41421356])

In [5]:
Vt

array([[ 0.70710678,  0.        ,  0.70710678,  0.        ],
       [ 0.        ,  0.70710678,  0.        ,  0.70710678],
       [-0.70710678,  0.        ,  0.70710678,  0.        ],
       [ 0.        , -0.70710678,  0.        ,  0.70710678]])

In [6]:
S= np.resize(S,[2,1])*np.eye(2,4)
S

array([[1.41421356, 0.        , 0.        , 0.        ],
       [0.        , 1.41421356, 0.        , 0.        ]])

In [17]:
US=np.dot(U,S)

In [18]:
USV=np.dot(np.dot(U,S),Vt)
USV

array([[1., 0., 1., 0.],
       [0., 1., 0., 1.]])

In [19]:
np.dot(U,S)

array([[1.41421356, 0.        , 0.        , 0.        ],
       [0.        , 1.41421356, 0.        , 0.        ]])

In [20]:
np.dot(S,Vt)

array([[1., 0., 1., 0.],
       [0., 1., 0., 1.]])

In [15]:
np.sqrt(2)

1.4142135623730951

In [22]:
A=[[1, 2],[2,1]]
A

[[1, 2], [2, 1]]

In [24]:
U, S, Vt = svd(A)
S

array([3., 1.])

In [32]:
XtX=np.transpose(A).dot(A)
eig_val, eig_vec = np.linalg.eig(XtX)
eig_val

array([2., 0., 2., 0.])